version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  get-jobs:
    build:
      dockerfile: Dockerfile
    command: npm run start-getJobs
    depends_on:
      - app
    networks:
      - mynetwork

  create-jobs:
    build:
      dockerfile: Dockerfile
    command: npm run start-createJobs
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    
